{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "AdventureWorksDW2016",
        "connectionString": "Provider=SQLNCLI11;Data Source=SQLSERVER2017;Persist Security Info=false;Integrated Security=SSPI;Initial Catalog=AdventureWorksDW2016",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "Excel Sales Manager",
        "connectionString": "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\\SQLServer2017BI\\Lab01\\Starter\\Data\\Sales Manager.xlsx;Persist Security Info=false;Extended Properties=\"Excel 12.0;HDR=Yes;\"",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "Excel"
          }
        ]
      },
      {
        "type": "structured",
        "name": "File/D:\\SQLServer2017BI\\Lab01\\Assets\\Targets csv",
        "connectionDetails": {
          "protocol": "file",
          "address": {
            "path": "D:\\SQLServer2017BI\\Lab01\\Assets\\Targets.csv"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "kind": "File",
          "path": "d:\\sqlserver2017bi\\lab01\\assets\\targets.csv"
        },
        "contextExpression": [
          "let",
          "    #\"0001\" = Csv.Document(..., [Delimiter = \",\", Columns = 14, Encoding = 65001, QuoteStyle = QuoteStyle.None]),",
          "    #\"0002\" = Table.PromoteHeaders(#\"0001\", [PromoteAllScalars = true]),",
          "    #\"0003\" = Table.TransformColumnTypes(#\"0002\", {{\"Year\", Int64.Type}, {\"EmployeeKey\", Int64.Type}, {\"M01\", Int64.Type}, {\"M02\", Int64.Type}, {\"M03\", Int64.Type}, {\"M04\", Int64.Type}, {\"M05\", Int64.Type}, {\"M06\", Int64.Type}, {\"M07\", Int64.Type}, {\"M08\", Int64.Type}, {\"M09\", Int64.Type}, {\"M10\", Int64.Type}, {\"M11\", Int64.Type}, {\"M12\", Int64.Type}})",
          "in",
          "    #\"0003\""
        ]
      }
    ],
    "tables": [
      {
        "name": "Product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product"
          },
          {
            "name": "Subcategory",
            "dataType": "string",
            "sourceColumn": "Subcategory"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "displayFolder": "Stocking"
          },
          {
            "name": "Size",
            "dataType": "int64",
            "sourceColumn": "Size",
            "displayFolder": "Stocking",
            "encodingHint": "hash"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight",
            "displayFolder": "Stocking",
            "encodingHint": "value"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class",
            "displayFolder": "Stocking"
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style",
            "displayFolder": "Stocking"
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "source": {
              "query": [
                "SELECT",
                "  DimProduct.ProductKey",
                "  ,DimProduct.EnglishProductName AS Product",
                "  ,DimProductSubcategory.EnglishProductSubcategoryName AS Subcategory",
                "  ,DimProductCategory.EnglishProductCategoryName AS Category",
                "  ,DimProduct.Color",
                "  ,CASE WHEN ISNUMERIC(DimProduct.Size) = 1 THEN CAST(DimProduct.Size AS INT) ELSE NULL END AS Size",
                "  ,DimProduct.Weight",
                "  ,DimProduct.Class",
                "  ,DimProduct.Style",
                "FROM",
                "  DimProductSubcategory",
                "  INNER JOIN DimProduct",
                "    ON DimProductSubcategory.ProductSubcategoryKey = DimProduct.ProductSubcategoryKey",
                "  INNER JOIN DimProductCategory",
                "    ON DimProductSubcategory.ProductCategoryKey = DimProductCategory.ProductCategoryKey",
                "WHERE",
                "  DimProduct.FinishedGoodsFlag = 1;"
              ],
              "dataSource": "AdventureWorksDW2016"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  DimProduct.ProductKey",
                  "  ,DimProduct.EnglishProductName AS Product",
                  "  ,DimProductSubcategory.EnglishProductSubcategoryName AS Subcategory",
                  "  ,DimProductCategory.EnglishProductCategoryName AS Category",
                  "  ,DimProduct.Color",
                  "  ,CASE WHEN ISNUMERIC(DimProduct.Size) = 1 THEN CAST(DimProduct.Size AS INT) ELSE NULL END AS Size",
                  "  ,DimProduct.Weight",
                  "  ,DimProduct.Class",
                  "  ,DimProduct.Style",
                  "FROM",
                  "  DimProductSubcategory",
                  "  INNER JOIN DimProduct",
                  "    ON DimProductSubcategory.ProductSubcategoryKey = DimProduct.ProductSubcategoryKey",
                  "  INNER JOIN DimProductCategory",
                  "    ON DimProductSubcategory.ProductCategoryKey = DimProductCategory.ProductCategoryKey",
                  "WHERE",
                  "  DimProduct.FinishedGoodsFlag = 1;</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Products",
            "levels": [
              {
                "name": "Category",
                "ordinal": 0,
                "column": "Category"
              },
              {
                "name": "Subcategory",
                "ordinal": 1,
                "column": "Subcategory"
              },
              {
                "name": "Product",
                "ordinal": 2,
                "column": "Product"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Product"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  DimProduct.ProductKey",
              "  ,DimProduct.EnglishProductName AS Product",
              "  ,DimProductSubcategory.EnglishProductSubcategoryName AS Subcategory",
              "  ,DimProductCategory.EnglishProductCategoryName AS Category",
              "  ,DimProduct.Color",
              "  ,CASE WHEN ISNUMERIC(DimProduct.Size) = 1 THEN CAST(DimProduct.Size AS INT) ELSE NULL END AS Size",
              "  ,DimProduct.Weight",
              "  ,DimProduct.Class",
              "  ,DimProduct.Style",
              "FROM",
              "  DimProductSubcategory",
              "  INNER JOIN DimProduct",
              "    ON DimProductSubcategory.ProductSubcategoryKey = DimProduct.ProductSubcategoryKey",
              "  INNER JOIN DimProductCategory",
              "    ON DimProductSubcategory.ProductCategoryKey = DimProductCategory.ProductCategoryKey",
              "WHERE",
              "  DimProduct.FinishedGoodsFlag = 1;"
            ]
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  DimProduct.ProductKey",
              "  ,DimProduct.EnglishProductName AS Product",
              "  ,DimProductSubcategory.EnglishProductSubcategoryName AS Subcategory",
              "  ,DimProductCategory.EnglishProductCategoryName AS Category",
              "  ,DimProduct.Color",
              "  ,CASE WHEN ISNUMERIC(DimProduct.Size) = 1 THEN CAST(DimProduct.Size AS INT) ELSE NULL END AS Size",
              "  ,DimProduct.Weight",
              "  ,DimProduct.Class",
              "  ,DimProduct.Style",
              "FROM",
              "  DimProductSubcategory",
              "  INNER JOIN DimProduct",
              "    ON DimProductSubcategory.ProductSubcategoryKey = DimProduct.ProductSubcategoryKey",
              "  INNER JOIN DimProductCategory",
              "    ON DimProductSubcategory.ProductCategoryKey = DimProductCategory.ProductCategoryKey",
              "WHERE",
              "  DimProduct.FinishedGoodsFlag = 1;</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sales Region",
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "Sales Region",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryRegion"
          }
        ],
        "partitions": [
          {
            "name": "Sales Region",
            "source": {
              "query": "SELECT [dbo].[DimSalesTerritory].[SalesTerritoryKey],[dbo].[DimSalesTerritory].[SalesTerritoryRegion] FROM [dbo].[DimSalesTerritory]  WHERE (NOT(([SalesTerritoryRegion] = N'NA')) OR [SalesTerritoryRegion] IS NULL)",
              "dataSource": "AdventureWorksDW2016"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;141&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryAlternateKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;195&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryRegion&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;160&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryCountry&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;169&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryGroup&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;156&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryImage&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;156&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryAlternateKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryRegion&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryCountry&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;3&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryGroup&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;4&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryImage&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;5&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryAlternateKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryRegion&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryCountry&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryGroup&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryImage&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnChecked&gt;",
                  "  &lt;ColumnFilter&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryRegion&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;FilterExpression xsi:nil=\"true\" /&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnFilter&gt;",
                  "  &lt;SelectionFilter&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryRegion&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;SelectionFilter&gt;",
                  "          &lt;SelectionType&gt;Deselect&lt;/SelectionType&gt;",
                  "          &lt;Items&gt;",
                  "            &lt;anyType xsi:type=\"xsd:string\"&gt;NA&lt;/anyType&gt;",
                  "          &lt;/Items&gt;",
                  "        &lt;/SelectionFilter&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/SelectionFilter&gt;",
                  "  &lt;FilterParameters&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SalesTerritoryRegion&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;CommandParameters /&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/FilterParameters&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales Region Count",
            "expression": "COUNTA([Sales Region])",
            "formatString": "0",
            "detailRowsDefinition": {}
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimSalesTerritory"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "  SELECT [dbo].[DimSalesTerritory].[SalesTerritoryKey],[dbo].[DimSalesTerritory].[SalesTerritoryRegion] FROM [dbo].[DimSalesTerritory]  WHERE (NOT(([SalesTerritoryRegion] = N'NA')) OR [SalesTerritoryRegion] IS NULL) "
          }
        ]
      },
      {
        "name": "Reseller Sales",
        "defaultDetailRowsDefinition": {
          "expression": [
            "SELECTCOLUMNS(",
            "\t'Reseller Sales',",
            "\t\"Order Date\", [OrderDate],",
            "\t\"Sales Rep\", RELATED('Sales Rep'[Sales Rep]),",
            "\t\"Product\", RELATED('Product'[Product]),",
            "\t\"Sales\", [Sales]",
            ")   "
          ]
        },
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "Price",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "UnitPrice",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\" xmlns=\"\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "SalesAmount",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\" xmlns=\"\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "OrderDate"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          }
        ],
        "partitions": [
          {
            "name": "Reseller Sales",
            "source": {
              "query": " SELECT [dbo].[FactResellerSales].[ProductKey],[dbo].[FactResellerSales].[EmployeeKey],[dbo].[FactResellerSales].[SalesTerritoryKey],[dbo].[FactResellerSales].[UnitPrice],[dbo].[FactResellerSales].[SalesAmount],[dbo].[FactResellerSales].[OrderDate] FROM [dbo].[FactResellerSales] ",
              "dataSource": "AdventureWorksDW2016"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>ProductKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DueDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShipDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ResellerKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EmployeeKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PromotionKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CurrencyKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesTerritoryKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesOrderNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>120</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesOrderLineNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>139</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RevisionNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderQuantity</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UnitPrice</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>72</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ExtendedAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UnitPriceDiscountPct</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DiscountAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ProductStandardCost</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>133</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TotalProductCost</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TaxAmt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>67</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Freight</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CarrierTrackingNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>140</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CustomerPONumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>127</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DueDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>72</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShipDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>ProductKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DueDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShipDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ResellerKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EmployeeKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PromotionKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CurrencyKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesTerritoryKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesOrderNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesOrderLineNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RevisionNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderQuantity</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UnitPrice</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ExtendedAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UnitPriceDiscountPct</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DiscountAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ProductStandardCost</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TotalProductCost</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TaxAmt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Freight</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CarrierTrackingNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CustomerPONumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DueDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShipDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>DueDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShipDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ResellerKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EmployeeKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PromotionKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CurrencyKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesOrderNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesOrderLineNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RevisionNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderQuantity</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ExtendedAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UnitPriceDiscountPct</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DiscountAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ProductStandardCost</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TotalProductCost</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TaxAmt</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Freight</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CarrierTrackingNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CustomerPONumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DueDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShipDate</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OrderDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales",
            "expression": "SUM([SalesAmount])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "Sales",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Average Price",
            "expression": "AVERAGE([Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "Sales\\Pricing",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Median Price",
            "expression": "MEDIAN([Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "Sales\\Pricing",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sales YoY%",
            "expression": [
              "",
              "VAR PreviousYearSales = CALCULATE([Sales], PARALLELPERIOD('Date'[Date], -12, MONTH))",
              "// Only return a value if PreviousYearSales is not empty",
              "RETURN IF(NOT ISBLANK(PreviousYearSales), DIVIDE([Sales] - PreviousYearSales, PreviousYearSales))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Sales",
            "detailRowsDefinition": {}
          },
          {
            "name": "RWB Sales",
            "expression": "CALCULATE([Sales], 'Product'[Color] IN {\"Red\", \"White\", \"Blue\"}) ",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "Sales",
            "detailRowsDefinition": {
              "expression": [
                "SELECTCOLUMNS(",
                "\t'Reseller Sales',",
                "\t\"Order Date\", [OrderDate],",
                "\t\"Sales Rep\", RELATED('Sales Rep'[Sales Rep]),",
                "\t\"Product\", RELATED('Product'[Product]),",
                "\t\"RWB Sales\", [RWB Sales]",
                ")"
              ]
            },
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "FactResellerSales"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[FactResellerSales].[ProductKey],[dbo].[FactResellerSales].[EmployeeKey],[dbo].[FactResellerSales].[SalesTerritoryKey],[dbo].[FactResellerSales].[UnitPrice],[dbo].[FactResellerSales].[SalesAmount],[dbo].[FactResellerSales].[OrderDate] FROM [dbo].[FactResellerSales] "
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>ProductKey</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DueDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShipDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ResellerKey</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EmployeeKey</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PromotionKey</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CurrencyKey</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesTerritoryKey</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesOrderNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>120</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesOrderLineNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>139</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RevisionNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderQuantity</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UnitPrice</string>",
              "      </key>",
              "      <value>",
              "        <int>72</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ExtendedAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UnitPriceDiscountPct</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DiscountAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ProductStandardCost</string>",
              "      </key>",
              "      <value>",
              "        <int>133</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TotalProductCost</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TaxAmt</string>",
              "      </key>",
              "      <value>",
              "        <int>67</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Freight</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CarrierTrackingNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>140</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CustomerPONumber</string>",
              "      </key>",
              "      <value>",
              "        <int>127</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderDate</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DueDate</string>",
              "      </key>",
              "      <value>",
              "        <int>72</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShipDate</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>ProductKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DueDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShipDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ResellerKey</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EmployeeKey</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PromotionKey</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CurrencyKey</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesTerritoryKey</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesOrderNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesOrderLineNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RevisionNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderQuantity</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UnitPrice</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ExtendedAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UnitPriceDiscountPct</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DiscountAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ProductStandardCost</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TotalProductCost</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TaxAmt</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Freight</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CarrierTrackingNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CustomerPONumber</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderDate</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DueDate</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShipDate</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>DueDateKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShipDateKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ResellerKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EmployeeKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PromotionKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CurrencyKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesOrderNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesOrderLineNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RevisionNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderQuantity</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ExtendedAmount</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UnitPriceDiscountPct</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DiscountAmount</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ProductStandardCost</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TotalProductCost</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TaxAmt</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Freight</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CarrierTrackingNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CustomerPONumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderDate</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DueDate</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShipDate</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OrderDateKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date"
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\"FY\" & YEAR([Date]) + IF(MONTH([Date]) > 6, 1, 0)"
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "YEAR([Date]) & \" \" & FORMAT([Date], \"mmm\")",
            "sortByColumn": "MonthKey"
          },
          {
            "type": "calculated",
            "name": "MonthKey",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "(YEAR([Date]) * 100) + MONTH([Date])"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALENDARAUTO(6)"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Fiscal",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Manager",
        "columns": [
          {
            "name": "Sales Region",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Region",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Sales Manager",
            "dataType": "string",
            "sourceColumn": "Sales Manager",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Sales Manager",
            "dataView": "full",
            "source": {
              "query": " \t\t\t\tSELECT ['Sales Manager$'].*   FROM ['Sales Manager$'] ",
              "dataSource": "Excel Sales Manager"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT ['Sales Manager$'].*   FROM ['Sales Manager$'] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "'Sales Manager$'"
          }
        ]
      },
      {
        "name": "Sales Rep",
        "columns": [
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ParentEmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ParentEmployeeKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Sales Rep",
            "dataType": "string",
            "sourceColumn": "Sales Rep"
          },
          {
            "type": "calculated",
            "name": "Path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH([EmployeeKey], [ParentEmployeeKey])"
          },
          {
            "type": "calculated",
            "name": "Level 1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE([Sales Rep], [EmployeeKey], PATHITEM([Path], 1, 1))"
          },
          {
            "type": "calculated",
            "name": "Level 2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE([Sales Rep], [EmployeeKey], PATHITEM([Path], 2, 1))"
          },
          {
            "type": "calculated",
            "name": "Level 3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE([Sales Rep], [EmployeeKey], PATHITEM([Path], 3, 1))"
          },
          {
            "type": "calculated",
            "name": "Level 4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE([Sales Rep], [EmployeeKey], PATHITEM([Path], 4, 1))"
          }
        ],
        "partitions": [
          {
            "name": "Sales Rep",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[DimEmployee].[EmployeeKey],[dbo].[DimEmployee].[ParentEmployeeKey],[dbo].[DimEmployee].[FirstName] + N' ' + [dbo].[DimEmployee].[LastName] AS [Sales Rep] FROM [dbo].[DimEmployee] WHERE ([SalesPersonFlag] = 1) OR ([EmployeeKey] IN (112, 277))",
              "dataSource": "AdventureWorksDW2016"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[DimEmployee].[EmployeeKey],[dbo].[DimEmployee].[ParentEmployeeKey],[dbo].[DimEmployee].[FirstName] + N' ' + [dbo].[DimEmployee].[LastName] AS [Sales Rep] FROM [dbo].[DimEmployee] WHERE ([SalesPersonFlag] = 1) OR ([EmployeeKey] IN (112, 277))</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Sales Organization",
            "hideMembers": "hideBlankMembers",
            "levels": [
              {
                "name": "Level 1",
                "ordinal": 0,
                "column": "Level 1"
              },
              {
                "name": "Level 2",
                "ordinal": 1,
                "column": "Level 2"
              },
              {
                "name": "Level 3",
                "ordinal": 2,
                "column": "Level 3"
              },
              {
                "name": "Level 4",
                "ordinal": 3,
                "column": "Level 4"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[DimEmployee].[EmployeeKey],[dbo].[DimEmployee].[ParentEmployeeKey],[dbo].[DimEmployee].[FirstName] + N' ' + [dbo].[DimEmployee].[LastName] AS [Sales Rep] FROM [dbo].[DimEmployee] WHERE ([SalesPersonFlag] = 1) OR ([EmployeeKey] IN (112, 277))"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimEmployee"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[DimEmployee].[EmployeeKey],[dbo].[DimEmployee].[ParentEmployeeKey],[dbo].[DimEmployee].[FirstName] + N' ' + [dbo].[DimEmployee].[LastName] AS [Sales Rep] FROM [dbo].[DimEmployee] WHERE ([SalesPersonFlag] = 1) OR ([EmployeeKey] IN (112, 277))</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Targets",
        "columns": [
          {
            "name": "Date",
            "dataType": "string",
            "sourceColumn": "Date"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "TargetAmount",
            "dataType": "double",
            "sourceColumn": "TargetAmount"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"File/D:\\SQLServer2017BI\\Lab01\\Assets\\Targets csv\",",
                "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(Source, {\"Year\", \"EmployeeKey\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Columns\",{{\"Attribute\", \"MonthNumber\"}, {\"Value\", \"TargetAmount\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each [TargetAmount] <> 0),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",\"M\",\"\",Replacer.ReplaceText,{\"MonthNumber\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"MonthNumber\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Date\", each #date([Year], [MonthNumber], 1)),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"Year\", \"MonthNumber\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns\",{\"Date\", \"EmployeeKey\", \"TargetAmount\"})",
                "in",
                "    #\"Reordered Columns\""
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "ec21eee5-2173-48c8-816c-8a23f992d8e3",
        "fromTable": "Reseller Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      },
      {
        "name": "3c699c61-5855-45cd-8e16-5d1ae8294d28",
        "fromTable": "Reseller Sales",
        "fromColumn": "OrderDate",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "479b1224-7c8f-4a05-9631-0aa2a6cf7ac1",
        "fromTable": "Reseller Sales",
        "fromColumn": "SalesTerritoryKey",
        "toTable": "Sales Region",
        "toColumn": "SalesTerritoryKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "6d6be7f6-b087-43ef-9d2a-44dfb264a1fd",
        "fromTable": "Sales Manager",
        "fromColumn": "Sales Region",
        "toTable": "Sales Region",
        "toColumn": "Sales Region",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "ec33476c-31a8-4a68-ac94-5987611e41f9",
        "fromTable": "Reseller Sales",
        "fromColumn": "EmployeeKey",
        "toTable": "Sales Rep",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "272e756e-abfb-4458-a9ac-307c3232985d",
        "fromTable": "Targets",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "f3e3980a-6c7e-4e3c-9909-1ccb4c92607a",
        "fromTable": "Targets",
        "fromColumn": "EmployeeKey",
        "toTable": "Sales Rep",
        "toColumn": "EmployeeKey"
      }
    ],
    "cultures": [
      {
        "name": "fr-FR",
        "translations": {
          "model": {
            "name": "Model",
            "translatedCaption": "Modle de Donnes",
            "tables": [
              {
                "name": "Product",
                "translatedCaption": "Produit",
                "columns": [
                  {
                    "name": "Product",
                    "translatedCaption": "Produit"
                  },
                  {
                    "name": "Subcategory",
                    "translatedCaption": "Sous-Catgorie"
                  },
                  {
                    "name": "Category",
                    "translatedCaption": "Catgorie"
                  },
                  {
                    "name": "Color",
                    "translatedCaption": "Couleur",
                    "translatedDisplayFolder": "Stock"
                  },
                  {
                    "name": "Size",
                    "translatedCaption": "Taille",
                    "translatedDisplayFolder": "Stock"
                  },
                  {
                    "name": "Weight",
                    "translatedCaption": "Poids",
                    "translatedDisplayFolder": "Stock"
                  },
                  {
                    "name": "Class",
                    "translatedCaption": "Classe",
                    "translatedDisplayFolder": "Stock"
                  },
                  {
                    "name": "Style",
                    "translatedCaption": "Modle",
                    "translatedDisplayFolder": "Stock"
                  }
                ],
                "hierarchies": [
                  {
                    "name": "Products",
                    "translatedCaption": "Produits",
                    "levels": [
                      {
                        "name": "Category",
                        "translatedCaption": "Catgorie"
                      },
                      {
                        "name": "Subcategory",
                        "translatedCaption": "Sous-Catgorie"
                      },
                      {
                        "name": "Product",
                        "translatedCaption": "Produit"
                      }
                    ]
                  }
                ]
              },
              {
                "name": "Sales Region",
                "translatedCaption": "Territoire Commercial",
                "columns": [
                  {
                    "name": "Sales Region",
                    "translatedCaption": "Territoire Commercial"
                  }
                ],
                "measures": [
                  {
                    "name": "Sales Region Count",
                    "translatedCaption": "Nombre de Territoires Commercials"
                  }
                ]
              },
              {
                "name": "Reseller Sales",
                "translatedCaption": "Ventes par Revendeur",
                "measures": [
                  {
                    "name": "Sales",
                    "translatedCaption": "Ventes",
                    "translatedDisplayFolder": "Ventes"
                  },
                  {
                    "name": "Average Price",
                    "translatedCaption": "Prix Moyen",
                    "translatedDisplayFolder": "Ventes\\Prix"
                  },
                  {
                    "name": "Median Price",
                    "translatedCaption": "Prix Mdian",
                    "translatedDisplayFolder": "Ventes\\Prix"
                  },
                  {
                    "name": "Sales YoY%",
                    "translatedCaption": "Ventes En Glissement Annuel%",
                    "translatedDisplayFolder": "Ventes"
                  }
                ]
              },
              {
                "name": "Date",
                "translatedCaption": "Temps",
                "columns": [
                  {
                    "name": "Year",
                    "translatedCaption": "Anne"
                  },
                  {
                    "name": "Month",
                    "translatedCaption": "Mois"
                  }
                ],
                "hierarchies": [
                  {
                    "name": "Fiscal",
                    "translatedCaption": "Fiscal",
                    "levels": [
                      {
                        "name": "Year",
                        "translatedCaption": "Anne"
                      },
                      {
                        "name": "Month",
                        "translatedCaption": "Mois"
                      }
                    ]
                  }
                ]
              },
              {
                "name": "Sales Manager",
                "translatedCaption": "Directeur Commercial",
                "columns": [
                  {
                    "name": "Sales Manager",
                    "translatedCaption": "Directeur Commercial"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "roles": [
      {
        "name": "Sales Rep",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Sales Manager",
            "metadataPermission": "none"
          },
          {
            "name": "Reseller Sales",
            "columnPermissions": [
              {
                "name": "Price",
                "metadataPermission": "none"
              }
            ]
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}